version: '2'

services:
  web:
    build: ./
    command: harp server --port 9000
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    restart: always

  medium:
    build: ./service
    command: yarn start
    ports:
      - "3000:3000"
    restart: always
